[plugin.video.ytchannels] 0.2.0
xbmc/repo-plugins pull request #2996
Opened 2020-07-05 19:35 UTC by mintsoft

### Description

Provide access to youtube channels like folders from within Kodi that are configured on Kodi separately from the youtube subscriptions on a specific account or similiar.

This was originally made by Natko1412, however his repository hasn't been updated in ages and it seems abandoned.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

2020-07-05 19:36 UTC, TravisBuddy commented
## Travis tests have failed
Hey @mintsoft,
please read the following log in order to understand the failure reason. There might also be some helpful tips along the way.
It'll be awesome if you fix what's wrong and commit the changes.

### 1st Build
<details>
  <summary>
    <strong>
     Expand here
    </strong>
  </summary>

```
INFO: Checking repository /home/travis/build/xbmc/repo-plugins/plugin.video.ytchannels
INFO: Checking add-on plugin.video.ytchannels
INFO: Created by natko1412,mintsoft
INFO: Addon id matches folder name
INFO: This is a new addon
INFO: Valid XML file found
WARN: For leia it is advised to set xbmc.python version to 2.26.0
INFO: Optional dependency script.module.youtube is not available in current repository
ERROR: ./plugin.video.ytchannels/addon.xml is marked as stand-alone executable
ERROR: ./plugin.video.ytchannels/LICENSE.txt is marked as stand-alone executable
ERROR: ./plugin.video.ytchannels/default.py is marked as stand-alone executable
ERROR: ./plugin.video.ytchannels/icon.png is marked as stand-alone executable
ERROR: ./plugin.video.ytchannels/changelog.txt is marked as stand-alone executable
ERROR: ./plugin.video.ytchannels/resources/settings.xml is marked as stand-alone executable
INFO: Image icon exists
ERROR: Image icon should be explicitly declared in addon.xml <assets>.
INFO: icon dimensions are fine 256x256
INFO: You might want to add a fanart
WARN: Complex entry point. Check: default.py | Counted lines: 537 | Lines allowed: 15
ERROR: We found 7 problems and 2 warnings, please check the logfile.
```
</details>
<br />

2020-07-05 22:03 UTC, enen92 requested changes
Please see comments.

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/addon.xml
> +		<summary lang="en">Watch your favourite youtube channels</summary>
en_gb

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +db_dir = xbmc.translatePath("special://database")
Sorry, add-ons can only write to the addondata/profile path

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/addon.xml
> +		<description lang="en">Watch your favourite youtube channels and organize them in folders.</description>
en_gb

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/addon.xml
> +		<platform>all</platform>
License missing, please use a spdx identifier for the license (GPL-2.0-only or GPL-2.0-or-later) depending on your license

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/addon.xml
> +	</extension>
Please define the assets pointing to your icon and fanart

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/addon.xml
> +	</extension>
Would be nice to add news also as an alternative to the change log

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +db_dir = xbmc.translatePath("special://profile/addon_data/"+addonID)
You're assigning a new path to the previous defined path

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +categories_list=[['Autos and vehicles','http://vidstatsx.com/youtube-top-100-most-viewed-autos-vehicles'],['Comedy','http://vidstatsx.com/youtube-top-100-most-viewed-comedy'],
Any strings presented on the UI need to be localized. Please move all strings to strings.po in the language folder

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +            ['Science & Tech','http://vidstatsx.com/youtube-top-100-most-viewed-science-tech'],['Shows','http://vidstatsx.com/youtube-top-100-most-viewed-shows'],
None of these links are working for me

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        fh = open(channelFile, 'r')
Always use pythons with statement when opening files:

```python
with open(file, mode) as fh:
    fh.something()
```

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        pDialog.create('Youtube Channels', 'Importing channels...')
Localise

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +                pDialog.update(75, 'Importing channels...')
Localise

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        pDialog.update(100, 'Importing channels...')
Localise

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        li = xbmcgui.ListItem('%s'%categories_list[i][0], iconImage='https://raw.githubusercontent.com/natko1412/repo.natko1412/master/img/folder.png')
Iconimage kwarg is deprecated and has been removed in matrix. Please use setArt

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        li = xbmcgui.ListItem('%s'%categories_list[i][0], iconImage='https://raw.githubusercontent.com/natko1412/repo.natko1412/master/img/folder.png')
Also please bundle this file with the add-on instead of pointing to github

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +            li = xbmcgui.ListItem('%s'%channel[0], iconImage='%s'%channel[2])
Iconimage is deprecated

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        else:
Not needed

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +            li = xbmcgui.ListItem('%s'%folders[i], iconImage='https://raw.githubusercontent.com/natko1412/repo.natko1412/master/img/folder.png')
Same

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +            li.addContextMenuItems([ ('Remove folder', 'RunPlugin(%s)'%rem_uri),
All this needs to be localized

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        li = xbmcgui.ListItem('Categories', iconImage='https://raw.githubusercontent.com/natko1412/repo.natko1412/master/img/category.png')
Same

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        li.addContextMenuItems([('Add folder', 'RunPlugin(%s)'%add_uri),
Same, all localised

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        li = xbmcgui.ListItem('Top Channels', iconImage='https://raw.githubusercontent.com/natko1412/repo.natko1412/master/img/top.png')
Same

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        li.addContextMenuItems([('Add folder', 'RunPlugin(%s)'%add_uri),
Same

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        li = xbmcgui.ListItem('%s'%channels[i][0], iconImage='%s'%channels[i][2])
Same

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        li.addContextMenuItems([('Remove channel', 'RunPlugin(%s)'%rem_uri),('Add folder', 'RunPlugin(%s)'%add_uri),
Same

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        li = xbmcgui.ListItem('[COLOR green]Add folder[/COLOR]', iconImage='https://raw.githubusercontent.com/natko1412/repo.natko1412/master/img/plus.png')
Same

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/resources/settings.xml
> +	<category label="API Key">
Is this still valid? YouTube data API has changed recently to only allow verified apps. @anxdpanic

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        xbmcgui.Dialog().ok("Youtube Channels", "Successfully erased folder database!")
Localise

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +elif mode[0]=='erase_all':
Localise

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +                xbmcgui.Dialog().ok("Youtube Channels", 'Channel with username "%s" does not exist.'%channel_name)
Same

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +
Same

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +    options=['Search for channel','Add by username']
Same

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        li = xbmcgui.ListItem('Next Page >>', iconImage=thumb)
Deprecated

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        li = xbmcgui.ListItem('%s'%name, iconImage='%s'%thumb)
Deprecated

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        li = xbmcgui.ListItem('Next Page >>', iconImage=thumb)
Deprecated

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        uri='plugin://plugin.video.youtube/play/?video_id='+video_id
If you need this, then the YouTube add-on cannot be an optional dependency

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        li = xbmcgui.ListItem('[COLOR yellow]Playlists [/COLOR]',iconImage='https://raw.githubusercontent.com/natko1412/repo.natko1412/master/img/playlist.png')
Deprecated

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +    li = xbmcgui.ListItem('[COLOR green]Add channel to[/COLOR][COLOR blue] %s[/COLOR]'%foldername, iconImage='https://raw.githubusercontent.com/natko1412/repo.natko1412/master/img/plus.png')
Deprecated

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        li = xbmcgui.ListItem('[COLOR green]Add channel to [/COLOR][COLOR blue] root[/COLOR]', iconImage='https://raw.githubusercontent.com/natko1412/repo.natko1412/master/img/plus.png')
Deprrcated

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        li.addContextMenuItems([('Add folder', 'RunPlugin(%s)'%add_uri),
Same. You seem to have a lot of repeated code

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        li = xbmcgui.ListItem('%s'%channels[i][0], iconImage='%s'%channels[i][2])
Deprecated

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +        li = xbmcgui.ListItem('[COLOR green]Add channel to [/COLOR][COLOR blue] root[/COLOR]', iconImage='https://raw.githubusercontent.com/natko1412/repo.natko1412/master/img/plus.png')
Deprecated

2020-07-05 22:03 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/default.py
> +elif mode[0]=='import':
Bad practice to keep all the plugin logic on the entry point file. This is not compiled to bytecode by Kodi python interpreter. Please.try to split up the code base and just import it in the entry point file

2020-07-06 07:10 UTC, mintsoft commented on plugin.video.ytchannels/plugin.video.ytchannels/resources/settings.xml
> +	<category label="API Key">
Hmm, it's working for me (using a different key). The default key here is the one that used to be hard-coded. It usually doesn't work (I've always assumed due to number of requests).  Plan is to make this actually prompt the user that they need to set their own key, I've left this for compatibility for now

2020-07-06 18:16 UTC, TravisBuddy commented
## Travis tests have failed
Hey @mintsoft,
please read the following log in order to understand the failure reason. There might also be some helpful tips along the way.
It'll be awesome if you fix what's wrong and commit the changes.

### 1st Build
<details>
  <summary>
    <strong>
     Expand here
    </strong>
  </summary>

```
INFO: Checking repository /home/travis/build/xbmc/repo-plugins/plugin.video.ytchannels
INFO: Checking add-on plugin.video.ytchannels
INFO: Created by natko1412,mintsoft,yeahme49
INFO: Addon id matches folder name
INFO: This is a new addon
failed validating 'en_gb' with XsdPatternFacets(['[a-z]{2,3}(_[A-Z]{2}(@\\S+)?)?']):

Reason: value doesn't match any pattern of ['[a-z]{2,3}(_[A-Z]{2}(@\\S+)?)?'].

Schema:

  <xs:pattern xmlns:xs="http://www.w3.org/2001/XMLSchema" value="[a-z]{2,3}(_[A-Z]{2}(@\S+)?)?" />

Instance:

  <summary lang="en_gb">Watch your favourite youtube channels</summary>

Path: /extension/summary

failed validating 'en_gb' with XsdPatternFacets(['[a-z]{2,3}(_[A-Z]{2}(@\\S+)?)?']):

Reason: value doesn't match any pattern of ['[a-z]{2,3}(_[A-Z]{2}(@\\S+)?)?'].

Schema:

  <xs:pattern xmlns:xs="http://www.w3.org/2001/XMLSchema" value="[a-z]{2,3}(_[A-Z]{2}(@\S+)?)?" />

Instance:

  <description lang="en_gb">Watch your favourite youtube channels and organize them in folders.</description>

Path: /extension/description

ERROR: Schema validation failed for the following points: xbmc.addon.metadata 
WARN: Required dependency plugin.video.youtube does not require a minimum version, available: 6.8.2
INFO: Image icon exists
INFO: icon dimensions are fine 256x256
INFO: You might want to add a fanart
INFO: PO files are valid
ERROR: We found 1 problems and 1 warnings, please check the logfile.
```
</details>
<br />

2020-07-06 18:31 UTC, TravisBuddy commented
## Travis tests were successful
Hey @mintsoft,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-07-06 18:32 UTC, mintsoft commented
@enen92 All fixed up I think, the Travis build is passing now as well

2020-07-07 08:45 UTC, enen92 approved these changes

2020-07-07 08:46 UTC, enen92 commented on plugin.video.ytchannels/plugin.video.ytchannels/resources/settings.xml
> +<?xml version="1.0" encoding="utf-8" standalone="yes"?>
Ups sorry, I missed this one. All the strings that are hardcoded in english need to be also localized

2020-07-07 08:46 UTC, enen92 requested changes
Please fix settings.xml with localisable strings

2020-07-07 20:15 UTC, mintsoft commented
@enen92 settings.xml done :)

2020-07-07 20:15 UTC, TravisBuddy commented
## Travis tests were successful
Hey @mintsoft,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-07-07 20:53 UTC, enen92 approved these changes

2020-07-07 20:53 UTC, merged

2020-07-08 05:05 UTC, mintsoft commented
Thanks @enen92

2020-07-08 07:50 UTC, enen92 commented
Thank you for submitting and maintaining the addon :)