[plugin.video.cbc] 4.0.6+matrix.1
xbmc/repo-plugins pull request #3038
Opened 2020-07-30 02:42 UTC by micahg

### Description
Matrix compatible version of the CBC addon.
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

2020-07-30 02:43 UTC, TravisBuddy commented
## Travis tests were successful
Hey @micahg,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-07-30 02:45 UTC, TravisBuddy commented
## Travis tests were successful
Hey @micahg,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-07-31 12:18 UTC, enen92 requested changes
Only minors

2020-07-31 12:18 UTC, enen92 commented on plugin.video.cbc/addon.xml
> +    <summary lang="en">CBC TV Kodi Plugin</summary>
en_GB

2020-07-31 12:18 UTC, enen92 commented on plugin.video.cbc/addon.xml
> +    <description lang="en">View online content from the Canadian Broadcasting Corporation.</description>
en_GB

2020-07-31 12:18 UTC, enen92 commented on plugin.video.cbc/addon.xml
> +    <disclaimer lang="en">For bugs, requests or general questions visit the CBC TV thread on the Kodi forum.</disclaimer>
en_GB

2020-07-31 12:18 UTC, enen92 commented on plugin.video.cbc/addon.xml
> +    <language>en</language>
Keep this as en

2020-07-31 12:18 UTC, enen92 commented on plugin.video.cbc/addon.xml
> +    <license>GNU GENERAL PUBLIC LICENSE. Version 2, June 1991</license>
Please use a spdx compliant identifier. Should be GPL-2.0-only or GPL-2.0-or-later depending on your interest. See spdx.org

2020-08-10 01:03 UTC, micahg commented
en_GBs should be fixed. Thanks.

2020-08-10 01:04 UTC, TravisBuddy commented
## Travis tests were successful
Hey @micahg,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-08-11 00:31 UTC, micahg commented
Do I have to do something to remove that label? Developer has responded.

Thanks,

2020-08-13 09:54 UTC, enen92 approved these changes
All good codewise. I'll ask some american based people if there are any issues we should be aware regarding this particular broadcaster

2020-08-13 12:14 UTC, merged

2020-08-13 18:41 UTC, micahg commented
hey @enen92 I'm pretty sure this wont be available in the US -- is there something I should add to it to indicate so?

2020-08-13 18:44 UTC, enen92 commented
No, appart from language we have no way of filtering add-ons in the UI I'm afraid. Maybe this is something we should keep in mind as a future Kodi feature