[plugin.video.crackle] 2020.10.1
xbmc/repo-plugins pull request #3133
Opened 2020-10-01 13:36 UTC by eracknaphobia

### Description

        - Update code for Python3
        - Improve Sorting of list items (thanks ssreekanth)
        - Add DRM playback support (Allows for HD streams)
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

2020-10-01 13:38 UTC, TravisBuddy commented
## Travis tests were successful
Hey @eracknaphobia,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-10-02 08:37 UTC, enen92 commented on plugin.video.crackle/.gitattributes
> +# Auto detect text files and perform LF normalization
please drop from submission. If you're automating submission try to add to .gitatttributes

2020-10-02 08:37 UTC, enen92 commented on plugin.video.crackle/.gitignore
> +# Windows image file caches
same

2020-10-02 08:38 UTC, enen92 commented on plugin.video.crackle/addon.xml
> +    <license>GNU GENERAL PUBLIC LICENSE. Version 2, June 1991</license>
spdx identifier here if possible: GPL-2.0-only or GPL-2.0-or-later

2020-10-02 08:39 UTC, enen92 requested changes
Minors, after those fixes can be merged. Thanks for the update!

2020-10-03 11:56 UTC, TravisBuddy commented
## Travis tests were successful
Hey @eracknaphobia,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-10-03 12:01 UTC, eracknaphobia commented
@enen92 Ok, I think I got everything. Thanks for the review!

2020-10-03 12:25 UTC, enen92 approved these changes

2020-10-03 12:25 UTC, merged