[plugin.video.redbull.tv@matrix] 3.2.0+matrix.1
xbmc/repo-plugins pull request #3186
Opened 2020-10-29 10:01 UTC by piejanssens

### Add-on details:

- **General**
  - Add-on name: Red Bull TV
  - Add-on ID: plugin.video.redbull.tv
  - Version number: 3.2.0+matrix.1
  - Kodi/repository version: matrix

- **Code location**
  - URL: https://github.com/add-ons/plugin.video.redbull.tv
  
Red Bull TV gives you front-row access to live events, the best inaction sports, new music and entertainment, and thrilling videos from world adventurers.

### Description of changes:

v3.2.0
- Support VOD playback from EPG via context menu
- Add YouTube integration (requires YouTube add-on)
- Improve channel listing
- New add-on icon

v3.1.0
- IPTV Manager support

v3.0.0
- Harder, Better, Faster, Stronger
    

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

2020-10-29 10:32 UTC, TravisBuddy commented
## Travis tests were successful
Hey @piejanssens,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-10-30 21:40 UTC, enen92 requested changes

2020-10-30 21:40 UTC, enen92 commented on plugin.video.redbull.tv/addon.xml
> +    <summary lang="en">Watch Red Bull TV, live and on demand.</summary>
en_GB here and the 2 lines below

2020-10-30 21:40 UTC, enen92 commented on plugin.video.redbull.tv/addon.xml
> +    </disclaimer>
License field missing, please add one with a spdx identifier

2020-10-30 21:40 UTC, enen92 commented on plugin.video.redbull.tv/resources/lib/addon.py
> +                plot='Best of Red Bull TV',
Please localize

2020-10-30 21:40 UTC, enen92 commented on plugin.video.redbull.tv/resources/lib/addon.py
> +    executebuiltin('Container.SetViewMode({mode})'.format(mode=55))  # Wide List
Not allowed in the repo, please drop this call

2020-11-01 21:40 UTC, TravisBuddy commented
## Travis tests were successful
Hey @piejanssens,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-11-01 21:43 UTC, piejanssens commented
Hi @enen92,

Thanks for your review. 
I belief I have addressed your remarks. for both the Leia and Matrix PR.

P

2020-11-01 21:58 UTC, enen92 approved these changes

2020-11-01 21:58 UTC, merged