[plugin.video.streamz@matrix] 1.0.0+matrix.1
xbmc/repo-plugins pull request #3202
Opened 2020-11-03 16:06 UTC by michaelarnauts

### Add-on details:

- **General**
  - Add-on name: Streamz
  - Add-on ID: plugin.video.streamz
  - Version number: 1.0.0+matrix.1
  - Kodi/repository version: matrix

- **Code location**
  - URL: https://github.com/add-ons/plugin.video.streamz
  
Streamz is a video-on-demand platform offering Flemish content from DPG Media, Telenet and VRT, but also including 'Home of HBO' content and blockbuster movies.

### Description of changes:

v1.0.0 (2020-11-03)
- Initial release

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

2020-11-03 16:10 UTC, michaelarnauts commented
This addon is based on `plugin.video.vtm.go` what is already in the repo (for Leia). The code is really similar since they use the same backend, but it's a different service.

2020-11-03 17:04 UTC, TravisBuddy commented
## Travis tests were successful
Hey @michaelarnauts,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-11-14 10:13 UTC, enen92 commented on plugin.video.streamz/codecov.yml
> +coverage:
please drop (add to gitattributes as export-ignore if using CI/CD)

2020-11-14 10:18 UTC, enen92 requested changes
Code looks okay and ready to merge. The coverage test file has to go though

2020-11-14 11:45 UTC, michaelarnauts commented
> Code looks okay and ready to merge. The coverage test file has to go though

Ow. Sorry. I've missed this. Is it okay to add the CHANGELOG? There have been comments about that in the past, but then I've read somewhere that it's okay to include them.

2020-11-14 11:54 UTC, enen92 commented
Changelog is fine

2020-11-14 12:46 UTC, michaelarnauts commented
> Changelog is fine but please keep the news tag in add-on.xml for your current version changes

Okay. Since this is the first actual release to the public, everything is new, so I've just put `Initial release` there. Usually, I put the most important changes there (since the actual changelog can be a bit technical).

2020-11-14 12:58 UTC, enen92 approved these changes

2020-11-14 12:59 UTC, merged

2020-11-14 13:04 UTC, michaelarnauts commented
Thanks @enen92!