Matrix plugin.audio.pureradio 3.0.2
xbmc/repo-plugins pull request #3203
Opened 2020-11-04 12:18 UTC by bdommel

Update for Kodi 19+
- Complete rewrite based on guidelines for Kodi
- Python3 support
- Podcast section optimalisations. Retrieval is much faster and optional (via add-on settings) artwork can be shown.

Many thanks to the Kodi Team for their support and making this awesome application possible.

2020-11-04 12:32 UTC, TravisBuddy commented
## Travis tests were successful
Hey @bdommel,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-11-05 17:42 UTC, learningit commented
You need to squash all these commits down into a single commit for submission. Please have a look at this for how to do it:

https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

2020-11-06 14:24 UTC, TravisBuddy commented
## Travis tests were successful
Hey @bdommel,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-11-09 21:28 UTC, bdommel commented
As far as I can see, the squashing of the commits is done.

2020-11-09 21:43 UTC, enen92 commented
It is not, still 15 commits but don't worry about it. We can squash them when merging.

2020-11-09 21:44 UTC, enen92 commented on LICENSE.txt
> +
This file is not contained within your addon folder

2020-11-09 21:45 UTC, enen92 requested changes
Actually you should care. You're removing files from the matrix repository and adding files outside the folder of your addon...

2020-11-09 21:45 UTC, enen92 commented on README.md
> -![Kodi logo](https://raw.githubusercontent.com/xbmc/xbmc/master/media/banner.png)
Please fix your pull request

2020-11-10 10:37 UTC, bdommel commented
This squashing of the commits gave strange results. Still trying to see why I got a commit history on a new branche with a single commit. I will do a new commit and pull request.

2020-11-10 10:37 UTC, closed without merging