[plugin.video.yelo@leia] 1.0.1
xbmc/repo-plugins pull request #3229
Opened 2020-12-03 18:48 UTC by shycoderX

### Add-on details:

- **General**
  - Add-on name: Yelo
  - Add-on ID: plugin.video.yelo
  - Version number: 1.0.1
  - Kodi/repository version: leia

- **Code location**
  - URL: https://github.com/add-ons/plugin.video.yelo
  
This plugin makes it possible to watch live streams that are available on the Telenet Yelo application for your region.

### Description of changes:

v1.0.1 (2020-11-02)
- Add Kodi 19 checks @shycoderX)
- Load EPG in the background (@shycoderX)
- Add device registration for Play subscription (@fripsy)
- Use sock.sendall instead of sock.send (@michaelarnauts)

### v1.0.0 (2020-05-22)
- Add Dutch translations (@dagwieers)
- Add support for IPTV Manager (@shycoderX, @dagwieers)
        

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

2020-12-03 21:47 UTC, enen92 requested changes

2020-12-03 21:47 UTC, enen92 commented on plugin.video.yelo/.github/workflows/addon-check.yml
> +# This workflow performs the required add-on checks for a submission
Please drop from the submission. If using ci/cd add it to gitattributes as export-ignore

2020-12-03 21:47 UTC, enen92 commented on plugin.video.yelo/.github/workflows/ci.yml
> +# This workflow performs the various sanity tests, integration tests and
Same

2020-12-03 21:47 UTC, enen92 commented on plugin.video.yelo/.github/workflows/release.yml
> +# This workflow performs an automated release to GitHub and to the official
Same

2020-12-03 21:47 UTC, enen92 commented on plugin.video.yelo/addon.xml
> +        <source>https://github.com/add-ons/plugin.video.yelo</source>
Can you change the license to a spdx compatible identifier? Should be GPL-3.0-only

2020-12-04 08:36 UTC, michaelarnauts commented on plugin.video.yelo/resources/lib/README.md
> +# Readme
You should also remove this file.

2020-12-04 16:30 UTC, shycoderX commented
Ok now?

2020-12-04 19:49 UTC, enen92 approved these changes

2020-12-04 19:50 UTC, merged