[plugin.video.newyankeeworkshop] 0.0.3
xbmc/repo-plugins pull request #3258
Opened 2020-12-19 03:10 UTC by th0ma5w

### Description
Updated code to Python 3

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

2020-12-19 03:36 UTC, th0ma5w commented
After studying this some more, perhaps this should be a Matrix-only commit... let me know and I can resubmit this on that branch only, or is Krypton expected to also receive Python 3?

2020-12-19 09:47 UTC, enen92 commented on plugin.video.newyankeeworkshop/addon.xml
> +		<import addon="xbmc.python" version="3.0.0"/>
Can't do this. Addons with xbmc.python 3.0.0 should be submitted to the matrix branch

2020-12-19 09:48 UTC, enen92 requested changes
Please keep this one as is and submit a new version to matrix.
Thanks

2020-12-21 00:35 UTC, th0ma5w commented
Will submit a new pull request against the Matrix branch

2020-12-21 00:35 UTC, closed without merging