[plugin.video.newyankeeworkshop] 0.0.3
xbmc/repo-plugins pull request #3267
Opened 2020-12-21 00:39 UTC by th0ma5w

### Description
  - Updated the plugin for Matrix to use Python 3.x
### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

2020-12-26 11:35 UTC, enen92 commented on plugin.video.newyankeeworkshop/addon.xml
> +		<import addon="xbmc.addon" version="18.9.701" />
please drop the xbmc.addon dependency

2020-12-26 11:38 UTC, enen92 commented on plugin.video.newyankeeworkshop/router.py
> +        li.setArt({'icon': os.path.join(ADDON_PATH,'icon.png')})
maybe pass the whole dict to the setArt call? You'd avoid calling setArt multiple times which has a performance penalty.

2020-12-26 11:38 UTC, enen92 requested changes
See comments. Thanks for the update

2020-12-29 22:15 UTC, th0ma5w commented
All requested changes have been made. Thank you so much for the feedback, and I do think it is actually noticeably faster.

2020-12-29 22:25 UTC, enen92 approved these changes

2020-12-29 22:25 UTC, merged