[plugin.video.media-ccc-de@matrix] v0.2.0+matrix.1
xbmc/repo-plugins pull request #3279
Opened 2020-12-24 13:53 UTC by TobiX

### Description

This is the same as #3275, just for matrix. The changes are [minimal](https://github.com/voc/plugin.video.media-ccc-de/compare/matrix), since I have been writing PY2/3 compatible code for years (and there isn't much string handling in the add-on anyways)

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

2020-12-24 14:29 UTC, enen92 commented on plugin.video.media-ccc-de/addon.xml
> +    <license>MIT License</license>
MIT only please (spdx identifier)

2020-12-24 14:30 UTC, enen92 commented on plugin.video.media-ccc-de/resources/lib/recording.py
> +        print("Requested quality %s and format %s" % (quality, format))
Drop the print and use xbmc.log only

2020-12-24 14:30 UTC, enen92 commented on plugin.video.media-ccc-de/resources/lib/stream.py
> +        print("Requested quality %s and format %s" % (quality, format))
Same

2020-12-24 14:31 UTC, enen92 requested changes
Minimal changes needed. Thanks for submitting to matrix.
We wish you a merry Christmas ⛄

2020-12-24 23:13 UTC, TobiX commented
Put all logging calls into a simple wrapper (so my tests still run 😁), so the calls should now be correct when running inside Kodi

2020-12-25 22:44 UTC, enen92 approved these changes

2020-12-25 22:44 UTC, merged