[plugin.audio.ampache@matrix] 1.2.1+matrix.1
xbmc/repo-plugins pull request #3334
Opened 2021-01-28 19:33 UTC by lusum

### Description

**Add-on details:**

*General*

- Add-on name: Kodi Ampache plugin
-  Add-on ID: plugin.audio.ampache
- Version number: 1.2.1-matrix.1
- Kodi/repository version: matrix

Code location
- URL: https://github.com/ampache/ampache-xbmc-plugin

New plugin, official ampache server/nexcloud music plugin for kodi

1.2.1 (27.01.2021)

    Apply changes to be included in the official kodi repo plugin

### Checklist:

- [ ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

2021-01-28 19:37 UTC, enen92 commented
Are you somehow using our GitHub action scripts to do auto submissions? If so, you don't need to close and create a new pull request. Simply deleting a tag (locally and remote) and tagging it again with the same tag will push a new update to all your open pull requests

2021-01-28 19:46 UTC, enen92 requested changes

2021-01-28 19:46 UTC, enen92 commented on plugin.audio.ampache/resources/lib/ampache_connect.py
> +            xbmc.executebuiltin("ConnectionError" )
This builtin doesn't exist afaik..

2021-01-28 19:46 UTC, enen92 commented on plugin.audio.ampache/resources/lib/ampache_connect.py
> +            xbmc.executebuiltin("ConnectionError" )
Same

2021-01-28 19:46 UTC, enen92 commented on plugin.audio.ampache/resources/lib/ampache_connect.py
> +            xbmc.executebuiltin("ConnectionError" )
Same

2021-01-28 19:46 UTC, enen92 commented on plugin.audio.ampache/resources/lib/ampache_plugin.py
> +    x.join()
I don't think this is right, X is a new thread instance each time you iterate on the for loop. You're only waiting for the last one to finish and not all of them. Save a thread reference into a list and execute join on all of them after the loop ends

2021-01-28 20:02 UTC, lusum commented
>Are you somehow using our GitHub action scripts to do auto submissions? If so, you don't need to close and create a new pull request. Simply deleting a tag (locally and remote) and tagging it again with the same tag will push a new update to all your open pull requests

This is my first pull, so i fear to make a mess and i delete everything, but i can try

>xbmc.executebuiltin("ConnectionError" )

Ok, i will cancel and i will test the new code

>I don't think this is right, X is a new thread instance each time you iterate on the for loop. You're only waiting for the last one to finish and not all of them. Save a thread reference into a list and execute join on all of them after the loop ends

Ok, thanks, i will make the change, it doesn't change the overall behaviour, but it is more correct.

2021-01-30 20:13 UTC, lusum commented
close now,

2021-01-30 20:13 UTC, closed without merging