[plugin.video.comingsoon.it@matrix] 1.2.1+matrix.1
xbmc/repo-plugins pull request #3382
Opened 2021-02-21 17:57 UTC by phate89

### Add-on details:

- **General**
  - Add-on name: Comingsoon Trailer
  - Add-on ID: plugin.video.comingsoon.it
  - Version number: 1.2.1+matrix.1
  - Kodi/repository version: matrix

- **Code location**
  - URL: https://github.com/phate89/plugin.video.comingsoon.it
  
Watch the shows and the complete episodes from the website www.comingsoon.it

### Description of changes:

v1.2.1
Fixed addon after page changes

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

2021-02-21 18:37 UTC, enen92 commented on plugin.video.comingsoon.it/addon.xml
> +    <email></email>
drop if empty

2021-02-21 18:37 UTC, enen92 approved these changes

2021-02-21 22:36 UTC, enen92 requested changes
See comment regarding the email element

2021-02-21 23:45 UTC, phate89 commented
Dropped the empty tag

2021-03-13 18:27 UTC, enen92 requested changes

2021-03-13 18:27 UTC, enen92 commented on plugin.video.comingsoon.it/addon.xml
> +    <summary lang="it">Guarda i traiiler dei film da www.comingsoon.it</summary>
it_IT

2021-03-13 18:27 UTC, enen92 commented on plugin.video.comingsoon.it/addon.xml
> +	<summary lang="en">Watch trailers from www.comingsoon.it</summary>
en_GB

2021-03-13 18:27 UTC, enen92 commented on plugin.video.comingsoon.it/addon.xml
> +    <description lang="it">Visualizza i trailer dei film in sala e in arrivo dal sito www.comingsoon.it</description>
it_IT

2021-03-13 18:27 UTC, enen92 commented on plugin.video.comingsoon.it/addon.xml
> +	<description lang="en">Watch the shows and the complete episodes from the website www.comingsoon.it</description>
en_GB

2021-03-14 16:35 UTC, enen92 commented
ping @phate89

2021-03-15 09:04 UTC, phate89 commented
I dropped the old style lines and now they should be ok

2021-04-02 20:37 UTC, enen92 commented
`ERROR: Version mismatch for required dependency script.module.phate89, required: 2.0.1, Available: 1.2.1+matrix.1`

2021-04-06 15:15 UTC, phate89 commented
I fixed the wrong dependency version. thanks!

2021-04-07 22:41 UTC, merged