[plugin.video.eitb] 2.0.0
xbmc/repo-plugins pull request #3385
Opened 2021-02-23 06:50 UTC by erral

### Description
This is an update of the already existing plugin.video.eitb plugin for Kodi Matrix
### Checklist:
- [x ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

2021-02-23 22:00 UTC, basrieter requested changes
Could you look into the comments I gave.

2021-02-23 22:00 UTC, basrieter commented on plugin.video.eitb/.gitignore
> +# Byte-compiled / optimized / DLL files
Please exclude from submission.

2021-02-23 22:00 UTC, basrieter commented on plugin.video.eitb/addon.xml
> +        <license>GNU General Public License, v3</license>
Could you use the SPDX code for the license. See https://spdx.org/licenses/

`GPL-3.0-only`  or `GPL-3.0-or-later`

2021-02-24 07:01 UTC, erral commented
I have made the requested changes. Thanks!

2021-02-24 20:05 UTC, basrieter approved these changes

2021-02-24 20:05 UTC, merged