[plugin.video.sarpur] 5.0.0
xbmc/repo-plugins pull request #3395
Opened 2021-02-24 20:04 UTC by Dagur

### Description
Converted existing plugin to python3 and updated addon.xml and folder structure to comply with new setup rules

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

2021-02-26 22:01 UTC, enen92 commented on plugin.video.sarpur/addon.xml
> +        <email></email>
drop if empty

2021-02-26 22:01 UTC, enen92 commented on plugin.video.sarpur/addon.xml
> +        <summary lang="en">Play media off the Icelandic Public Radio's website</summary>
en_GB

2021-02-26 22:01 UTC, enen92 commented on plugin.video.sarpur/addon.xml
> +        <description lang="en">An Icelandic IP-Address is required to use this because of geoblocking</description>
en_GB

2021-02-26 22:02 UTC, enen92 commented on plugin.video.sarpur/addon.xml
> +        <import addon="script.module.simplejson" version="2.0.10"/>
please remove simplejson dependency, no longer needed. Use json only.

2021-02-26 22:02 UTC, enen92 commented on plugin.video.sarpur/addon.xml
> +        <news>Version 5.0 (2021-02-23)
please keep this only for the latest version

2021-02-26 22:04 UTC, enen92 requested changes
Minors

2021-02-27 09:35 UTC, Dagur commented
Thanks for the review. I've updated addon.xml. Should i create a new PR or is this fine?

2021-02-27 09:41 UTC, enen92 commented
This one is fine

2021-02-27 09:41 UTC, enen92 approved these changes

2021-02-27 09:42 UTC, merged