[plugin.video.putio] 3.0.0
xbmc/repo-plugins pull request #3428
Opened 2021-03-02 17:18 UTC by BatuAksoy

### Description
This commit migrates existing putio add-on to matrix. See old add-on here: https://github.com/xbmc/repo-plugins/tree/helix/plugin.video.putio
- Updated xbmc.python to 3.0.0
- Removed/Updated python2 specific codes
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

2021-03-02 20:55 UTC, enen92 requested changes
See comments

2021-03-02 20:55 UTC, enen92 commented on plugin.video.putio/addon.xml
> +        <license>GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007</license>
GPL-3.0-only or GPL-3.0-or-later instead of the full name

2021-03-02 20:55 UTC, enen92 commented on plugin.video.putio/addon.xml
> +        <forum></forum>
Drop if empty

2021-03-02 20:55 UTC, enen92 commented on plugin.video.putio/main.py
> +                (I18N(32042), 'XBMC.RunPlugin(%s)' % delete_ctx_url))  # delete context
Drop xbmc prefix, no longer valid

2021-03-02 20:55 UTC, enen92 commented on plugin.video.putio/resources/__init__.py
> +# -*- coding: utf-8 -*-
Shouldn't be needed anymore in python3

2021-03-02 20:55 UTC, enen92 commented on plugin.video.putio/resources/lib/__init__.py
> +# -*- coding: utf-8 -*-
Same

2021-03-03 09:33 UTC, BatuAksoy commented
Thank you for your review and feedbacks @enen92.
Now it should be okay

2021-03-03 09:35 UTC, enen92 approved these changes

2021-03-03 09:35 UTC, enen92 commented
Thanks for adjusting

2021-03-03 09:35 UTC, merged