[plugin.audio.eco99music] 0.0.6
xbmc/repo-plugins pull request #3429
Opened 2021-03-02 22:14 UTC by noamsto

### Description

Made eco99music addon to be compatible with Kodi 19. Originally introduced [here](https://github.com/xbmc/repo-plugins/pull/1338). 

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

2021-03-03 09:10 UTC, enen92 requested changes
See comments, minors. Good to go afterwards.
Thanks for the update

2021-03-03 09:10 UTC, enen92 commented on plugin.audio.eco99music/addon.py
> +            os.path.join(ADDON_FOLDER, 'resources/media/fanart.jpg')
```suggestion
            os.path.join(ADDON_FOLDER, 'resources', 'media', 'fanart.jpg')
```

2021-03-03 09:10 UTC, enen92 commented on plugin.audio.eco99music/addon.xml
> +        <license>GNU GENERAL PUBLIC LICENSE. Version 3, 29 June 2007</license>
```suggestion
        <license>GPL-3.0-only</license>
```

2021-03-03 09:11 UTC, enen92 commented
Please check also travis failures: https://travis-ci.com/github/xbmc/repo-plugins/builds/218778708

2021-03-06 20:38 UTC, noamsto commented on plugin.audio.eco99music/addon.py
> +            os.path.join(ADDON_FOLDER, 'resources/media/fanart.jpg')
Done

2021-03-06 20:38 UTC, noamsto commented on plugin.audio.eco99music/addon.xml
> +        <license>GNU GENERAL PUBLIC LICENSE. Version 3, 29 June 2007</license>
Done

2021-03-14 16:35 UTC, enen92 approved these changes
Sorry for the delay

2021-03-14 16:35 UTC, merged