[plugin.video.lbry] 0.1.3
xbmc/repo-plugins pull request #3432
Opened 2021-03-03 16:28 UTC by accumulator

### Description
Update of plugin.video.lbry from Leia to Matrix

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

2021-03-03 22:50 UTC, enen92 requested changes
See comments

2021-03-03 22:50 UTC, enen92 commented on plugin.video.lbry/resources/language/strings.pot
> +msgid ""
this file is incorrect, remove it

2021-03-03 22:50 UTC, enen92 commented on plugin.video.lbry/resources/lib/local.py
> +    return xbmc.translatePath(ADDON.getAddonInfo('profile') + rpath)
```suggestion
    return xbmcvfs.translatePath(ADDON.getAddonInfo('profile') + rpath)
```

2021-03-03 22:50 UTC, enen92 commented on plugin.video.lbry/resources/lib/exception.py
> +# -*- coding: utf-8 -*-
empty/dummy `__init__.py` files should no longer be needed in python3

2021-03-03 22:50 UTC, enen92 commented on plugin.video.lbry/resources/lib/local.py
> +        f = xbmcvfs.File(get_profile_path('channel_subs'), 'w')
jfyi `xbmcvfs.File` does support context lib, so you should be able to use:

```python
with xbmcvfs.File(get_profile_path('channel_subs'), 'w') as f:
    f.something()
``` 

Not mandatory to change though.

2021-03-04 10:07 UTC, accumulator commented
@enen92 issues resolved

2021-03-04 10:39 UTC, enen92 approved these changes

2021-03-04 10:39 UTC, merged