[plugin.audio.radiothek] 0.1.2
xbmc/repo-plugins pull request #3453
Opened 2021-03-13 13:56 UTC by s0faking

### Description
fixed broken livestreams, added livestream settings, added sort on podcast views
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

2021-03-13 14:14 UTC, enen92 requested changes

2021-03-13 14:14 UTC, enen92 commented on plugin.audio.radiothek/resources/lib/Addon.py
> +    addonUserDataFolder = xbmcvfs.translatePath("special://profile/addon_data/plugin.audio.radiothek")
This is not compatible with leia

2021-03-13 14:14 UTC, enen92 commented on plugin.audio.radiothek/resources/lib/Addon.py
> +    addonUserDataFolder = xbmcvfs.translatePath("special://profile/addon_data/plugin.audio.radiothek")
Same

2021-03-13 14:38 UTC, enen92 commented on plugin.audio.radiothek/resources/lib/Helpers.py
> +def radiothek_log(msg, debug=False):
sorry debug must be the default

2021-03-13 21:32 UTC, enen92 approved these changes

2021-03-13 21:33 UTC, enen92 commented
@s0faking can you revise?

2021-03-14 14:00 UTC, s0faking commented
> @s0faking can you rebase?

@enen92 do you mean "Resolve conflicts"? when i did that the last time i had 2 commits :( sorry my git skills are quite limited ;)

2021-03-14 14:12 UTC, enen92 commented
No problem with having two commits, we can then squash them

2021-03-21 17:10 UTC, enen92 commented
```
ERROR: plugin.audio.radiothek addon already exists with a lower or equal version: 0.1.2 in matrix branch and the addon has non forward abi compatible dependencies. Users migrating to kodi version matrix won't be able to receive the addon update.
```

2021-03-29 07:16 UTC, s0faking commented
> ```
> ERROR: plugin.audio.radiothek addon already exists with a lower or equal version: 0.1.2 in matrix branch and the addon has non forward abi compatible dependencies. Users migrating to kodi version matrix won't be able to receive the addon update.
> ```

sorry for the holdup. i already pushed a matrix version. i thought that i have to push one for matrix & leia because otherwise users with 18.x wouldnt get that update. or did i just push the updates in the wrong order?

2021-04-02 20:34 UTC, enen92 commented
@s0faking sorry for the delay. It looks the wrong order, the version in matrix should be always higher than the one in leia. So for this one to be valid, the version in matrix should be > 0.1.2, not equal. What you can do to keep the "same" versions is to append a localversion identifier to the matrix version. So:

matrix: 0.1.2+matrix.1
leia: 0.1.2

that way matrix > leia although the "same" version

2021-04-03 09:49 UTC, s0faking commented
> @s0faking sorry for the delay. It looks the wrong order, the version in matrix should be always higher than the one in leia. So for this one to be valid, the version in matrix should be > 0.1.2, not equal. What you can do to keep the "same" versions is to append a localversion identifier to the matrix version. So:
> 
> matrix: 0.1.2+matrix.1
> leia: 0.1.2
> 
> that way matrix > leia although the "same" version

i see. so i need to push a new matrix version before proceeding with the leia version right? on https://kodi.wiki/view/Addon.xml it says that the version attribute in the addon.xml should only contain text if its a beta version. is it ok anyway to add "~matrix" to the tag?

2021-04-03 09:57 UTC, enen92 commented
Yes, use x.x.x+matrix.1

2021-04-03 17:57 UTC, merged