[plugin.video.nfl.gamepass] 2021.03.14+matrix.1
xbmc/repo-plugins pull request #3462
Opened 2021-03-14 22:45 UTC by jm-duke

### Description
#### Addon
Name: NFL Game Pass
ID: plugin.video.nfl.gamepass
Version: 2021.03.14+matrix.1
Source: https://github.com/pigskin/kodi-gamepass

#### Info
NFL Game Pass is a service that allows those with subscriptions to watch NFL games. This add-on allows watching of live and past games via NFL's Game Pass service.

#### Updates
A previous version of this add-on was already contained in the Krypton repository. This version is the first to support Kodi 19.

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

2021-03-14 23:00 UTC, enen92 commented
Are you the new maintainer of this add-on/do you plan to keep updating the add-on?

2021-03-15 07:32 UTC, jm-duke commented
I joined forces with Alex as a new co-maintainer of the plugin. And yes, I plan to keep updating it.

2021-03-15 22:39 UTC, basrieter requested changes
I did a quick and initial check have some stuff that needs attention:

- `pigskin` is included as a complete module including the setup.py. I would suggest you submit a seperate script module add-on for this and reference it in your add-on. That way it is clear you are using external libraries.
- There are some unwanted files in your submission, please get rid of them. 
- It seems you are not the dev that submitted the most recent version (https://github.com/xbmc/repo-plugins/commit/45f49b15205ccfc052871e28c84d45919b6d30aa). So you will need to ask permisson from him/her before we will accept this PR.
- Please get rid of any deprecated call to `xbmc.....` Python modules, such as `xbmc.translatePath` .

Please **force push** changes here (no new PR needed), so we can keep this PR as the main one. After the above issues are resolved, I will checkout the code in more details.

2021-03-15 22:39 UTC, basrieter commented on plugin.video.nfl.gamepass/.gitignore
> +# Byte-compiled / optimized / DLL files
Remove from submission please.

2021-03-15 22:39 UTC, basrieter commented on plugin.video.nfl.gamepass/addon.xml
> +    <license>GNU GENERAL PUBLIC LICENSE. Version 2, June 1991</license>
Please use SPDX identifier: https://spdx.org/licenses/

2021-03-15 22:39 UTC, basrieter commented on plugin.video.nfl.gamepass/resources/lib/pigskin/LICENSE
> +MIT License
Why did you include the full `pigskin` module? Perhaps it makes more sense to include it as a seperate add-on module?

2021-03-15 22:39 UTC, basrieter commented on plugin.video.nfl.gamepass/default.py
> +ADDON_PATH = xbmc.translatePath(addon.getAddonInfo('path'))
Please use `xbmcvfs.translatePath()`, the `xbmc` version is deprecated.

2021-03-15 22:39 UTC, basrieter commented on plugin.video.nfl.gamepass/default.py
> +ADDON_PROFILE = xbmc.translatePath(addon.getAddonInfo('profile'))
Please use `xbmcvfs.translatePath()`, the `xbmc` version is deprecated.

2021-03-15 22:39 UTC, basrieter commented on plugin.video.nfl.gamepass/default.py
> +    response = xbmc.executeJSONRPC(json.dumps(payload))
Why not use `xbmc.getCondVisibility('System.HasAddon("inputstream.adaptive")')`. It will return `false` if not enabled.

2021-03-15 22:39 UTC, basrieter commented on plugin.video.nfl.gamepass/resources/lib/pigskin/setup.py
> +#!/usr/bin/env python
Please don't include `setup.py` it's not used at all.

2021-03-15 22:42 UTC, enen92 commented on plugin.video.nfl.gamepass/.github/ISSUE_TEMPLATE.md
> +<!--- We do not support setups which attempt to circumvent region restrictions
Any files in the .GitHub folder shouldn't be included in the submission

2021-03-15 22:47 UTC, basrieter commented
Please resubmit with correct naming into the correct repository, see my comments.

2021-03-15 22:47 UTC, closed without merging