[plugin.video.videomediaset@krypton] 2.0.4
xbmc/repo-plugins pull request #3530
Opened 2021-04-06 14:58 UTC by phate89

### Add-on details:

- **General**
  - Add-on name: Mediaset Play
  - Add-on ID: plugin.video.videomediaset
  - Version number: 2.0.4
  - Kodi/repository version: krypton

- **Code location**
  - URL: https://github.com/phate89/plugin.video.videomediaset
  
All your favorite shows are available to you the day after the airing Tv. Last night you missed your favorite TV drama? No problem, you can finally see her comfortably on KODI whenever you want.

### Description of changes:

2.0.4
- fixed loading of live channels and tv guide for a missing property (thx to madpilot78)
- removed workaround that created problems with loading seasons in shows like striscia
        

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

2021-04-10 21:18 UTC, enen92 approved these changes

2021-04-11 05:58 UTC, enen92 requested changes
Sorry version is wrong, you can't have two identical versions in krypton and matrix. Matrix has to be higher. Please set it to 2.0.6 in this pr.

2021-04-11 18:36 UTC, phate89 commented
Sorry for the mess I screwed up splitting the branches. Now it should be ok

2021-07-19 23:14 UTC, ronie approved these changes

2021-07-21 18:33 UTC, merged