[plugin.video.zoneminder] 3.0.0
xbmc/repo-plugins pull request #3549
Opened 2021-04-11 20:39 UTC by petegallagher

### Description
Update Zoneminder plugin for Kodi 19/Python 3.

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

2021-04-11 21:42 UTC, enen92 requested changes
Just the minor on the license

2021-04-11 21:42 UTC, enen92 commented on plugin.video.zoneminder/addon.xml
> +    <license>GPL-3.0</license>
GPL-3.0-only or GPL-3.0-or-later (please use a valid spdx identifier)

2021-04-11 21:42 UTC, enen92 commented on plugin.video.zoneminder/resources/settings.xml
> +<settings>
It'd be nice if you could update the settings to the new format. You could use https://gitlab.com/ronie/script.settings-convert for an automatic conversion

2021-06-01 11:18 UTC, petegallagher commented
@enen92 assuming this PR meets your requirements, can you squash these additional commits on merge?

2021-06-01 15:17 UTC, enen92 approved these changes

2021-06-01 15:18 UTC, merged