Addon for podcasts in Kodi Matrix
xbmc/repo-plugins pull request #3575
Opened 2021-05-01 19:44 UTC by Heckie75

### Description
This is an addon which you can use in order to subscribe to podcasts. However, it is not connected to any service. You just enter the URL auf the RSS File or to an OPML file which can be exported by podcasts receivers like AntennaPod. 

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

2021-05-01 19:57 UTC, basrieter commented
Please use the correct naming for the PR. Check the naming rules for PR: https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md

2021-05-01 20:25 UTC, Heckie75 commented
@basrieter Is the commit message better now?

2021-05-01 21:14 UTC, basrieter requested changes
Please check the comments I gave. I think there are more issues, but the add-on checker will point them out if it runs on this PR (transparent icons for instance).

The name of the PR should also be the equal to the commit name 😄

2021-05-01 21:14 UTC, basrieter commented on plugin.audio.podcasts/xmltodict.py
> +#!/usr/bin/env python
Please use `script.module.xmltodict` instead of including the script file alone.

2021-05-01 21:14 UTC, basrieter commented on plugin.audio.podcasts/addon.xml
> +		<license>MIT License</license>
Please use the SPDX identifier: https://spdx.org/licenses/

2021-05-01 21:14 UTC, basrieter commented on plugin.audio.podcasts/addon.xml
> +		<forum></forum>
Remove if empty or fill it correctly if it is required.

2021-05-01 21:14 UTC, basrieter commented on plugin.audio.podcasts/addon.xml
> +		<email></email>
Remove if empty or fill it correctly if it is required.

2021-05-01 21:14 UTC, basrieter commented on plugin.audio.podcasts/addon.py
> +            xbmc.executebuiltin("Notification(\"HTTP Status Error\", \"%s\")"
Please use `xbmcgui.Dialog().notification`

2021-05-01 21:14 UTC, basrieter commented on plugin.audio.podcasts/addon.py
> +            xbmc.executebuiltin("Notification(\"HTTP Status Error\", \"%s\")"
Please use xbmcgui.Dialog().notification

2021-05-01 21:14 UTC, basrieter commented on plugin.audio.podcasts/addon.py
> +        xbmc.executebuiltin('PlayMedia(%s)' % url)
I usually use `xbmcplugin.setResolvedUrl()` in combination with `xbmcgui.ListItem.setProperty('IsPlayable', 'true')`. That way Kodi will also remember what items were played in the past. But I guess this works. Same in other places.

2021-05-01 21:14 UTC, basrieter commented on plugin.audio.podcasts/addon.py
> +        if redirectCounter >= self._MAX_REDIRECTS:
I guess this works, but all of this could be taken care of by the `script.module.requests` module.

2021-05-01 21:14 UTC, basrieter commented on plugin.audio.podcasts/addon.xml
> +	<extension point="xbmc.python.pluginsource" library="addon.py">
```xml
<requires>
        <import addon="xbmc.python" version="3.0.0" />
</requires>
```
is missing.

2021-05-01 21:16 UTC, basrieter commented
Please also check the add-on checker issues: https://github.com/xbmc/repo-plugins/pull/3575/checks?check_run_id=2483927192

2021-05-02 09:21 UTC, Heckie75 commented
I close the PR since something went wrong based on my poor git experience

2021-05-02 09:21 UTC, closed without merging