[plugin.audio.sverigesradio] 3.0.0
xbmc/repo-plugins pull request #3622
Opened 2021-05-26 12:34 UTC by dodoadoodoo

### Description
Update to support matrix/python 3
### Checklist:

- [X ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

2021-06-10 20:45 UTC, sarbes requested changes

2021-06-10 20:45 UTC, sarbes commented on plugin.audio.sverigesradio/README
> +
An empty file?!

2021-06-10 20:45 UTC, sarbes commented on plugin.audio.sverigesradio/addon.xml
> +        <summary lang="en">Swedish National Radio (Sveriges Radio)</summary>
Wrong language identifiers.

2021-06-10 20:45 UTC, sarbes commented on plugin.audio.sverigesradio/resources/settings.xml
> +﻿<?xml version="1.0" encoding="utf-8" standalone="yes"?>
Just an FYI, this style might me outdated in the future: https://kodi.wiki/view/Add-on_settings_conversion

2021-06-11 06:45 UTC, dodoadoodoo commented on plugin.audio.sverigesradio/README
> +
Yeah, I got nothing to say :-) Do you recommend that I remove or should I add some boilerplate?

2021-06-11 06:45 UTC, dodoadoodoo commented on plugin.audio.sverigesradio/addon.xml
> +        <summary lang="en">Swedish National Radio (Sveriges Radio)</summary>
Fixed

2021-06-11 06:46 UTC, dodoadoodoo commented on plugin.audio.sverigesradio/resources/settings.xml
> +﻿<?xml version="1.0" encoding="utf-8" standalone="yes"?>
Thanks for the heads-up, will redo at some point in time

2021-07-19 23:21 UTC, ronie commented
looks good to me, thx!

2021-07-19 23:21 UTC, merged