[plugin.video.pcloud-video-streaming] 1.5.0
xbmc/repo-plugins pull request #3656
Opened 2021-06-24 13:52 UTC by gdomenici

### Description
Not a new addon - has been around for a while in other branches, but now I made it compatible with Matrix. Provides streaming for media files stored on pcloud.com.
### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

2021-06-27 20:42 UTC, romanvm requested changes
Please check the comments for `addon.xml` file. Other comments are not mandatory.

2021-06-27 20:42 UTC, romanvm commented on plugin.video.pcloud-video-streaming/addon.xml
> +    <summary lang="en">Provides streaming from a pcloud.com bucket</summary>
Should be `en_GB`

2021-06-27 20:42 UTC, romanvm commented on plugin.video.pcloud-video-streaming/resources/lib/pcloudapi.py
> +		if errorCode == 1000:
I recommend to use a `dict` mapping of error codes to messages instead of multiple `elif`s.

2021-06-27 20:42 UTC, romanvm commented on plugin.video.pcloud-video-streaming/resources/lib/pcloudapi.py
> +		if response["result"] != 0:
Simply `if response["result"]:`

2021-06-27 20:42 UTC, romanvm commented on plugin.video.pcloud-video-streaming/addon.xml
> +    <license>GNU GENERAL PUBLIC LICENSE. Version 3, June 2007</license>
Please use an [SDPX](https://spdx.org/licenses/) identifier.

2021-07-04 12:13 UTC, gdomenici commented on plugin.video.pcloud-video-streaming/resources/lib/pcloudapi.py
> +		if response["result"] != 0:
> 
> 
> Simply `if response["result"]:`

👍 thanks, fixed in a bunch of other places, too

2021-07-19 23:29 UTC, ronie requested changes

2021-07-19 23:29 UTC, ronie commented on plugin.video.pcloud-video-streaming/addon.xml
> +    <language>en_GB</language>
please revert this to
`<language>en</language>`

2021-07-19 23:29 UTC, ronie commented on plugin.video.pcloud-video-streaming/addon.xml
> +    <summary lang="en">Provides streaming from a pcloud.com bucket</summary>
please change it to:
`<summary lang="en_GB">`

2021-07-19 23:29 UTC, ronie commented on plugin.video.pcloud-video-streaming/addon.xml
> +    <description lang="en">Provides streaming from a pcloud.com video source. You need an account with pCloud to use this (free accounts are OK). Not affiliated with pcloud.com.</description>
`<description lang="en_GB">`

2021-07-19 23:29 UTC, ronie commented on plugin.video.pcloud-video-streaming/addon.xml
> +    <disclaimer lang="en">
should be: `<disclaimer lang="en_GB">`

2021-09-02 22:37 UTC, ronie commented
looks good to me, thx!

2021-09-02 22:37 UTC, merged