[plugin.video.lbry] v0.1.5+leia.1
xbmc/repo-plugins pull request #3732
Opened 2021-09-28 12:17 UTC by accumulator

### Description

- fix error in log statement
- fix exception thrown if channel contains a live stream
- add menu option to list recent videos from all subscribed channels
- add support for reading and posting comments

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

2021-09-30 06:38 UTC, romanvm approved these changes
LGTM

2021-09-30 20:22 UTC, basrieter commented
@accumulator  Please make the Add-on Checker happy and fix the error.

2021-09-30 20:22 UTC, basrieter requested changes
Please fix the add-on checker issue.

2021-10-01 16:23 UTC, enen92 commented on plugin.video.lbry/resources/skins/Default/skin.xml
> +<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
this file is no longer used by addons please remove from the submission

2021-10-01 16:24 UTC, enen92 requested changes
see comments

2021-10-05 07:33 UTC, closed without merging