[plugin.video.nhlgcl@jarvis] 2021.10.1
xbmc/repo-plugins pull request #3741
Opened 2021-10-04 14:36 UTC by eracknaphobia

### Add-on details:

- **General**
  - Add-on name: NHL TV™
  - Add-on ID: plugin.video.nhlgcl
  - Version number: 2021.10.1
  - Kodi/repository version: jarvis

- **Code location**
  - URL: https://github.com/eracknaphobia/plugin.video.nhlgcl
  
With NHL.TV you can access revolutionary 60fps (frames per second) video through Kodi
        

### Description of changes:

            - Add Seattle to Favorite Team selection
            - Refactor Fav Team code
            - Build game images dynamically
        

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

2021-10-09 21:34 UTC, basrieter requested changes
Please review my comment regarding modifying the add-on folders. (I do like the fact you are actually loading the files online instead of including them).

After that is fixed, I will review the rest.

2021-10-09 21:34 UTC, basrieter commented on plugin.video.nhlgcl/resources/lib/globals.py
> +        os.makedirs(folder_path)
You are not allowed to modify anything in the Kodi add-on folder. Not even your own add-on files. 

The best solution would be to store the images in the profile folder under `userdata\addon_data\plugin.video.nhlgcl`

2021-10-11 20:55 UTC, eracknaphobia commented on plugin.video.nhlgcl/resources/lib/globals.py
> +        os.makedirs(folder_path)
Ok, it should save the images in the addons user_data folder now.

2021-10-20 19:56 UTC, eracknaphobia commented on plugin.video.nhlgcl/resources/lib/globals.py
> +        os.makedirs(folder_path)
Any chance this one can be reviewed? The requested changes have been made.

2021-10-20 20:27 UTC, enen92 approved these changes

2021-10-20 20:29 UTC, merged