[plugin.video.nhlgcl@matrix] 2021.10.1+matrix.1
xbmc/repo-plugins pull request #3742
Opened 2021-10-04 14:36 UTC by eracknaphobia

### Add-on details:

- **General**
  - Add-on name: NHL TV™
  - Add-on ID: plugin.video.nhlgcl
  - Version number: 2021.10.1+matrix.1
  - Kodi/repository version: matrix

- **Code location**
  - URL: https://github.com/eracknaphobia/plugin.video.nhlgcl
  
With NHL.TV you can access revolutionary 60fps (frames per second) video through Kodi
        

### Description of changes:

            - Add Seattle to Favorite Team selection
            - Refactor Fav Team code
            - Build game images dynamically
        

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

2021-10-09 21:36 UTC, basrieter requested changes
Same comments as https://github.com/xbmc/repo-plugins/pull/3741

2021-10-14 13:05 UTC, eracknaphobia commented
@basrieter I've made the changes you requested. I'd appreciate a review when you get a chance.

2021-10-17 09:12 UTC, enen92 commented on plugin.video.nhlgcl/resources/lib/globals.py
> +USER_DATA_DIR = os.path.join(xbmc.translatePath("special://userdata"), 'addon_data', ADDON_ID)
xbmc.translatePath was already removed in nexus. Can you use xbmcvfs translatePath instead?

2021-10-17 09:13 UTC, enen92 requested changes
Just a small thing that needs changing and it's good to go

2021-10-17 13:29 UTC, eracknaphobia commented on plugin.video.nhlgcl/resources/lib/globals.py
> +USER_DATA_DIR = os.path.join(xbmc.translatePath("special://userdata"), 'addon_data', ADDON_ID)
I believe line 19 thru 22 should handle the conversion.

2021-10-17 14:16 UTC, enen92 commented on plugin.video.nhlgcl/resources/lib/globals.py
> +USER_DATA_DIR = os.path.join(xbmc.translatePath("special://userdata"), 'addon_data', ADDON_ID)
You're right, didn't spot that in the phone. Redefining Kodi built-in module behaviour is not a good practice though. Consider wrapping this into a function at some point in the future

2021-10-17 14:47 UTC, enen92 approved these changes

2021-10-17 14:47 UTC, merged