[plugin.video.skyvideoitalia] 1.0.1
xbmc/repo-plugins pull request #3752
Opened 2021-10-12 19:13 UTC by nixxo

### Description

Plugin update:
- added missing logos (removed unused)
- added getSettingAsInt
- added LOCAL_MAP
- improved simplecache usage (custom time set for different use)
- improved cleanTitle (clean if it starts with playlist title)
- better notification ID > NAME
- improved media url check
- moved libraries from resources to libs
- ~~added .gitignore and~~ removed garbage

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

2021-10-17 09:05 UTC, enen92 commented on plugin.video.skyvideoitalia/.gitignore
> +# Byte-compiled / optimized / DLL files
Please don't submit the gitignore as part of the submission

2021-10-17 09:06 UTC, enen92 requested changes
Code looks fine, gitignore has to go. Thanks

2021-11-09 19:03 UTC, nixxo commented
up

2021-11-10 19:35 UTC, enen92 approved these changes

2021-11-10 19:35 UTC, enen92 commented on plugin.video.skyvideoitalia/libs/skyitalia.py
> +                if url != '':
(suggestion) if url:

2021-11-10 19:35 UTC, merged

2021-11-10 19:35 UTC, enen92 commented
Sorry for the time taken, work has been quite busy lately.

2021-11-10 20:31 UTC, nixxo commented
no problem. Thanks for your time.