[plugin.video.orftvthek@leia] 0.12.4
xbmc/repo-plugins pull request #3892
Opened 2022-02-11 17:12 UTC by s0faking

### Add-on details:

- **General**
  - Add-on name: ORF TVthek
  - Add-on ID: plugin.video.orftvthek
  - Version number: 0.12.4
  - Kodi/repository version: leia

- **Code location**
  - URL: https://github.com/s0faking/plugin.video.orftvthek
  
ORF TVthek - This plugin provides access to the Austrian "ORF TVthek"

### Description of changes:

v0.12.4 (30/01/2022)
            [fix] fixed drm content (license server error 500)
        

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

2022-02-14 22:31 UTC, basrieter submitted a review, later dismissed
Please fix the "resolve" issue.

2022-02-14 22:31 UTC, basrieter commented on plugin.video.orftvthek/resources/lib/Addon.py
> +                xbmc.Player().play(streaming_url, play_item)
It should work and the `xbmc.Player().play()` should not be used. You are missing a `play_item.setProperty("IsPlayable", "true")`.

2022-02-14 22:35 UTC, basrieter requested changes
Please fix the "resolve" issue.

2022-02-15 12:20 UTC, s0faking commented
> Please fix the "resolve" issue.

i tried it. this doesn't work. i'm getting "Attempt to use invalid handle -1" messages but the video won't play. i only need this in on the restart option for livestreams. i'm  not sure but i think this happens here because this restart is launched from the context-menu of a livestream (via RunPlugin()). enen92 already looked into this issue some time ago. not sure but i think he opened an issue on the kodi core for this.

2022-02-15 20:12 UTC, basrieter commented
> > Please fix the "resolve" issue.
> 
> i tried it. this doesn't work. i'm getting "Attempt to use invalid handle -1" messages but the video won't play. i only need this in on the restart option for livestreams. i'm not sure but i think this happens here because this restart is launched from the context-menu of a livestream (via RunPlugin()). enen92 already looked into this issue some time ago. not sure but i think he opened an issue on the kodi core for this.

@enen92 can you confirm this?

2022-02-27 21:46 UTC, enen92 commented
Yeah that's right, playlist limitations on the API, we could well have s method for that in kodi

2022-02-28 12:58 UTC, basrieter approved these changes

2022-03-02 22:19 UTC, merged