[plugin.program.bluetoothctl] 1.0.1
xbmc/repo-plugins pull request #3912
Opened 2022-03-06 14:29 UTC by JimMadge

### Description

Interact with Bluetooth devices in Kodi using [the Linux Bluetooth stack](http://www.bluez.org/).

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

2022-03-06 15:52 UTC, lrusak commented
Why not just use the bluez dbus API instead of calling a binary using subprocess?

For an example see how LibreELEC does it. https://github.com/LibreELEC/service.libreelec.settings/blob/master/resources/lib/dbus_bluez.py

2022-03-07 19:30 UTC, JimMadge commented
I'm not familiar with D-Bus.

I didn't notice bluez had a D-Bus API. It looks like a better long-term solution, although it would mean adding Python D-Bus bindings as a dependency.

2022-10-10 13:19 UTC, pkscout requested changes

2022-10-10 13:19 UTC, pkscout commented on plugin.program.bluetoothctl/addon.py
> +from functools import wraps
It's not good form to have the entire program logic loaded by the file called from the addon.xml (in this case addon.py).  That file in never cached, so there is a significant performance hit.  Instead, import from a different file and just call it from addon.py.

2022-10-10 13:19 UTC, pkscout commented on plugin.program.bluetoothctl/resources/lib/bluetoothctl.py
> +from __future__ import annotations
the empty __init__.py file is not needed with Python3 and should be removed.  This also applies for the ones in the resources and lib folders.

2022-10-10 13:19 UTC, pkscout commented on plugin.program.bluetoothctl/resources/lib/bluetoothctl.py
> +from subprocess import CompletedProcess
Just noting this from the other comment.  Rather than using subprocess and call a binary, you should use the dbus API.

2024-09-08 14:35 UTC, closed without merging