[plugin.video.invidious] 0.1.0+matrix.1
xbmc/repo-plugins pull request #3927
Opened 2022-03-19 10:03 UTC by mintsoft

### Description

Invidious plugin for Kodi. A privacy-friendly way of viewing YouTube videos, built using the awesome Invidious service's API. 

This isn't my plugin, however I have agreement from the developer to package it for the main repository (https://github.com/TheAssassin/kodi-invidious-plugin/issues/10)

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

2022-03-19 19:00 UTC, anxdpanic requested changes
Thank you for the submission!

I left some comments, that require changes. 
I have to step away so I apologize if I missed anything on the first review.

2022-03-19 19:00 UTC, anxdpanic commented on plugin.video.invidious/README.md
> +# [Invidious](https://invidio.us) plugin for [Kodi](https://kodi.tv)
Please remove this file from the submission

2022-03-19 19:00 UTC, anxdpanic commented on plugin.video.invidious/addon.xml
> +        <language>en</language>
This is the language the add-on content is provided in, in this case would be `<language></language>` , since invidious should provide content in any language.

2022-03-19 19:00 UTC, anxdpanic commented on plugin.video.invidious/resources/lib/invidious_api.py
> +        print("========== request started ==========")
Please use `xbmc.log('message', xbmc.LOGDEBUG)` for logging instead of `print()`

2022-03-19 19:00 UTC, anxdpanic commented on plugin.video.invidious/resources/lib/invidious_api.py
> +        print("========== request finished in", end - start, "s ==========")
Please use `xbmc.log('message', xbmc.LOGDEBUG)`

2022-03-19 19:00 UTC, anxdpanic commented on plugin.video.invidious/resources/lib/invidious_plugin.py
> +        print("--------------------------------------------")
Please use `xbmc.log('message', xbmc.LOGDEBUG)`

2022-03-19 19:00 UTC, anxdpanic commented on plugin.video.invidious/addon.xml
> +        <description lang="en">A privacy-friendly way of watching YouTube content. Uses the great Invidious web
Use `"en_GB"`

2022-03-19 19:00 UTC, anxdpanic commented on plugin.video.invidious/resources/lib/invidious_api.py
> +                video.get("description", "No description available"),
Please localise if shown to the user

2022-03-19 19:00 UTC, anxdpanic commented on plugin.video.invidious/resources/lib/invidious_plugin.py
> +        search_input = dialog.input("Search", type=xbmcgui.INPUT_ALPHANUM)
Localise if shown to the user

2022-03-19 19:00 UTC, anxdpanic commented on plugin.video.invidious/resources/lib/invidious_plugin.py
> +        add_list_item("Search video titles", "search_video")
Localise if shown to the user

2022-03-19 19:00 UTC, anxdpanic commented on plugin.video.invidious/resources/lib/invidious_plugin.py
> +            dialog.notification(
Localise if shown to the user

2022-03-19 19:00 UTC, anxdpanic commented on plugin.video.invidious/resources/lib/invidious_plugin.py
> +            dialog.notification(
Localise if shown to the user

2022-03-19 19:00 UTC, anxdpanic commented on plugin.video.invidious/resources/settings.xml
> +<?xml version="1.0" encoding="utf-8" standalone="yes"?>
Just a suggestion, but I would update the settings xml format to v2.0
https://kodi.wiki/view/Add-on_settings_conversion

2022-03-19 19:00 UTC, anxdpanic commented on plugin.video.invidious/resources/settings.xml
> +        <setting label="Instance URL" type="text" id="instance_url" default="https://invidio.us"/>
Localise

2022-03-19 19:02 UTC, anxdpanic commented on plugin.video.invidious/addon.xml
> +        <description lang="en">A privacy-friendly way of watching YouTube content. Uses the great Invidious web
Just a heads up as well, the whitespace in description will be interpreted literally, so it may not appear as expected in Kodi as it is now.

2022-03-27 14:52 UTC, mintsoft commented
Cool, I'm just working through this list. Thanks

2022-03-30 20:52 UTC, mintsoft commented
I think I've resolved all that lot, so ready for another review whenever you are @anxdpanic

2022-04-08 01:28 UTC, anxdpanic commented
Sorry for the delay, if I haven't made any update to this by Sat. (9th) please feel free to ping me again. Hoping to get a chance tomorrow.

2022-04-08 19:39 UTC, anxdpanic approved these changes

2022-04-08 19:46 UTC, anxdpanic requested changes
Can you complete https://github.com/TheAssassin/kodi-invidious-plugin/issues/10, and have that merged. Then things should be good 👍

2022-04-09 19:44 UTC, mintsoft commented
Yeah no problem @anxdpanic

2022-04-10 00:29 UTC, TheAssassin commented
Merged.

2022-04-11 23:22 UTC, anxdpanic approved these changes

2022-04-11 23:23 UTC, anxdpanic commented
LGTM

Thanks!

2022-04-11 23:23 UTC, merged