[plugin.video.fosdem] 0.0.7
xbmc/repo-plugins pull request #3941
Opened 2022-04-05 19:43 UTC by jelly

### Description

### Checklist:

- [ ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

2022-04-05 21:58 UTC, basrieter requested changes
This PR look weird? Als if you are reverting Python 3 stuff, instead of introducing them?

2022-04-05 21:58 UTC, basrieter commented on plugin.video.fosdem/addon.xml
> +<addon id="plugin.video.fosdem" name="FOSDEM Videos" version="0.0.7" provider-name="Jelle van der Waa">
Is it correct that this is version 0.0.7 and the Krypton one is 0.0.8? That won't work. Most common is to version the Matrix version with "0.0.8+matrix.1" if the Krypton version is 0.0.8.

2022-04-05 21:58 UTC, basrieter commented on plugin.video.fosdem/resources/lib/addon.py
> +    return FORMATS[get_setting_int('format')]
The is an `Addon.getSettingInt()`. See https://romanvm.github.io/Kodistubs/_autosummary/xbmcaddon.html

2022-04-05 21:58 UTC, basrieter commented on plugin.video.fosdem/resources/settings.xml
> +<?xml version="1.0" encoding="utf-8" standalone="yes"?>
Why are you reverting back to the deprecated settings format?

2022-04-11 19:47 UTC, jelly commented
> This PR look weird? Als if you are reverting Python 3 stuff, instead of introducing them?

I guess I reverted that on my own branch because it was needed for the older supported kodi versions. I should I guess make branches for them so I don't move incompatible changes to older versions.

2022-04-13 21:03 UTC, basrieter commented
I guess so. If you fix up the Matrix PR, I can review it and then the Leia/Krypton version can be reviewed. That is the correct order.

2022-04-16 21:16 UTC, basrieter approved these changes

2022-04-16 21:16 UTC, merged