[plugin.video.maldivestv@matrix] 1.1.0
xbmc/repo-plugins pull request #4347
Opened 2023-06-29 16:46 UTC by jawish

### Add-on details:

- **General**
  - Add-on name: Maldives TV
  - Add-on ID: plugin.video.maldivestv
  - Version number: 1.1.0
  - Kodi/repository version: matrix

- **Code location**
  - URL: https://github.com/jawish/plugin.video.maldivestv
  
Kodi video plugin to view live streams of Maldives TV channels.

### Description of changes:

Initial release!

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

2023-07-05 08:27 UTC, romanvm commented
Please fix fanart size.

2023-07-05 08:27 UTC, romanvm requested changes

2023-07-05 08:27 UTC, romanvm commented on plugin.video.maldivestv/addon.xml
> +    <summary lang="en">Maldives TV</summary>
Please use 4-letter language codes: ll_CC, e.g. en_GB

2023-07-05 08:27 UTC, romanvm commented on plugin.video.maldivestv/addon.xml
> +    <license>GNU General Public License v2.0</license>
Please use a proper license code: https://spdx.org/licenses/

2024-08-25 12:40 UTC, basrieter commented
ping @jawish

2024-09-08 14:35 UTC, closed without merging