[plugin.video.raitv] 3.9.5
xbmc/repo-plugins pull request #4353
Opened 2023-07-22 07:49 UTC by maxbambi

### Description

this update of plugin:
- works with new menus of raiplay.it
- plays some protected videos with licenses from anycast.nagra.com 

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

2023-08-12 09:37 UTC, romanvm requested changes
Please fix log levels. Otherwise it's OK.

2023-08-12 09:37 UTC, romanvm commented on plugin.video.raitv/default.py
> +    xbmc.log("*******************************************************************************************************************",xbmc.LOGINFO)
It's better not to spam log with debug messages. Please use DEBUG log level.

2023-08-12 11:18 UTC, maxbambi commented on plugin.video.raitv/default.py
> +    xbmc.log("*******************************************************************************************************************",xbmc.LOGINFO)
@romanvm Debug level fixed

2023-08-14 08:16 UTC, romanvm approved these changes

2023-08-14 11:45 UTC, merged