[plugin.video.mlbtv@matrix] 2023.7.17+matrix.1
xbmc/repo-plugins pull request #4361
Opened 2023-07-27 19:58 UTC by eracknaphobia

### Add-on details:

- **General**
  - Add-on name: MLB.TV®
  - Add-on ID: plugin.video.mlbtv
  - Version number: 2023.7.17+matrix.1
  - Kodi/repository version: matrix

- **Code location**
  - URL: https://github.com/eracknaphobia/plugin.video.mlbtv
  
Watch every out-of-market regular season game in the office or on the go. The #1 LIVE
            Streaming Sports Service
        

### Description of changes:

            - option to hide scores ticker with black overlay
            - option to disable closed captions for games
            - fix gamechanger start/end time display
            - shorter estimated game lengths
            - improved recap detection
            - tweaked fox/national/all-star blackout detection
            - removed potential for double-proxied stream
        

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

2023-08-14 11:36 UTC, basrieter requested changes
Please try to remove some of the debug based logging.

2023-08-14 11:36 UTC, basrieter commented on plugin.video.mlbtv/resources/lib/mlbmonitor.py
> +        xbmc.log(monitor_name + " window size " + str(w) + "x" + str(h))
Could you remove these debug logging?

2023-08-23 16:05 UTC, eracknaphobia commented on plugin.video.mlbtv/resources/lib/mlbmonitor.py
> +        xbmc.log(monitor_name + " window size " + str(w) + "x" + str(h))
Ok, should be commented out now.

2023-08-28 20:50 UTC, romanvm approved these changes

2023-08-31 08:41 UTC, merged