[plugin.video.piped] 1.0.0
xbmc/repo-plugins pull request #4445
Opened 2024-01-06 00:44 UTC by syhlx

### Description
New addon which allows users to access any Piped instance, login and manage their playlists and watch history.

More information about Piped:
[Piped GitHub Repository](https://github.com/TeamPiped/Piped)
[Piped Official Instance](https://piped.video/)

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

2024-01-18 14:29 UTC, basrieter commented
Please fix the issues pointed out by the add-on checker. Then I will have a further look.

2024-01-18 19:10 UTC, syhlx commented
This should fix all the issues pointed out by the add-on checker

2024-01-21 18:25 UTC, basrieter requested changes
Could you have a look at the code for the services? It does not seem to handle aborts correctly.

2024-01-21 18:25 UTC, basrieter commented on plugin.video.piped/lib/services/entrypoint.py
> +		player.isPlaying()
Why this call? Makes no real sense if you don't use the output?

2024-01-21 18:25 UTC, basrieter commented on plugin.video.piped/lib/services/entrypoint.py
> +		while not self.abortRequested():
If `abortRequested()` results in `True`, the `httpservice` and `scheduler` aren't stopped properly and could cause Kodi to wait for a long time.

2024-01-21 18:25 UTC, basrieter commented on plugin.video.piped/lib/services/entrypoint.py
> +					xbmc.sleep(200)
If `scheduler.stop()` does not finish, the script waits for 200ms and then stops it again? In the `Scheduler.stop()` you call `self.join()` which should actually block until the thread stopped.

2024-01-22 09:17 UTC, syhlx commented
Before I commit anything, does this seem right to you?

```python
class Service(xbmc.Monitor):
  def __init__(self):
    httpservice = Thread(target=HttpService)
    scheduler = Scheduler()
    httpservice.daemon = True
    scheduler.daemon = True
    player = Player()

    while not self.waitForAbort(5):
      try:
        if not httpservice.is_alive(): httpservice.start()
        if not scheduler.is_alive(): scheduler.start()
      except:
        pass

    scheduler.stop()
```

2024-01-22 22:34 UTC, basrieter commented
Yes that makes more sense. Also make sure the `httpservice` is stopped in the line under the `scheduler.stop()`

2024-01-24 14:29 UTC, syhlx commented
Done

2024-02-11 10:52 UTC, basrieter approved these changes

2024-02-11 10:52 UTC, merged