[plugin.video.rtve]v1.0.0
xbmc/repo-plugins pull request #4591
Opened 2024-10-26 23:19 UTC by mcr222

### Description
Addon that takes the streams from Spanish public TV RTVE and lists all series and programs.

### Checklist:

- [ ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
- If you see no activity on your PR after a week (so at least one weekend has passed) then please go to the #kodi-dev freenode IRC channel to reach out to the team

2024-11-10 12:19 UTC, basrieter requested changes
Please check my comments. Main issue is that you are spamming the default loglevel far too much. Please fix that.

And make the add-on checker happy.

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/rtve/TestHtml.py
Please remove this file from your submission.

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/video/Video.py
> +        xbmc.log("plugin.video.rtve - video " + str(title) + ", " + str(url))
Remove this log please, or make it debug.

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/video/FolderVideo.py
> +        xbmc.log("plugin.video.rtve Creant folder video " + str(name) + ", " + str(url) + ", " + str(mode))
Remove this log or make it debug.

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/utils/Utils.py
> +        print(f"Error making request to {url}: {str(e)}")
Don't use print, but a proper `xbmc.log`.

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/utils/Utils.py
> +                print(error_msg)  # Log the error
Don't use `print`.

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/ui/UI.py
> +            xbmc.log("plugin.video.rtve - UI - playVideo widevine url" + str(license_url))
Please use a debug level here.

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/ui/UI.py
> +            xbmc.log(f'Error playing DRM stream: {str(e)}', xbmc.LOGERROR)
Use an error level here, instead of default loglevel

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/ui/UI.py
> +        xbmc.log("plugin.video.rtve - UI - playVideo apijson url" + str(stream_url))
Debug level here.

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/ui/UI.py
> +        xbmc.log("plugin.video.rtve -UI - playVideo " + str(videoId))
Debug level here.

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/ui/UI.py
> +            xbmc.log('Playback started successfully', xbmc.LOGINFO)
Debug level here.

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/ui/UI.py
> +        xbmc.log("plugin.video.rtve classe UI - listFolder")
Debug level here.

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/ui/UI.py
> +        xbmc.log("plugin.video.rtve - UI - listVideos - Numero videos: " + str(len(lVideos)))
Debug level here.

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/ui/UI.py
> +        xbmc.log("plugin.video.rtve classe UI - run()  mode = " + str(mode) + ", url " + str(url))
Debug level here.

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/rtve/rtve.py
> +        self.addon_path = addon_path
Why do you need the `addon_path`?

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/ui/UI.py
> +        addon_path = xbmcvfs.translatePath(addon.getAddonInfo('path'))
Why do you need the `addon_path`?

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/ui/UI.py
> +        xbmc.log("plugin.video.rtve classe UI - finish init()")
Debug level here.

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/ui/UI.py
> +            xbmc.log("plugin.video.rtve classe UI - mode = None")
Debug level here.

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/rtve/rtve.py
> +        xbmc.log("plugin.video.rtve classe rtve - listHome() ")
Debug level here.

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/rtve/rtve.py
> +        xbmc.log("plugin.video.rtve - programas " + urlApi)
Debug level here.

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/rtve/rtve.py
> +                    xbmc.log("plugin.video.rtve - element " + str(item))
Debug level here.

2024-11-10 12:19 UTC, basrieter commented on plugin.video.rtve/resources/lib/rtve/rtve.py
> +                    xbmc.log("plugin.video.rtve - element " + str(item))
Debug level here.

2024-11-18 22:01 UTC, mcr222 commented on plugin.video.rtve/resources/lib/ui/UI.py
> +        addon_path = xbmcvfs.translatePath(addon.getAddonInfo('path'))
just leftover from trials

2024-11-18 22:38 UTC, mcr222 commented
I think i found all logs and made them debug/error. Thanks for the feedback. Also fixed the  add-on checker issues.

2024-11-26 18:19 UTC, basrieter approved these changes

2024-11-26 18:19 UTC, basrieter commented
Thanks for you updates!

2024-11-26 18:19 UTC, merged