[plugin.switchback@nexus] 1.0.0
xbmc/repo-plugins pull request #4596
Opened 2024-11-10 23:50 UTC by bossanova808

### Add-on details:

- **General**
  - Add-on name: Switchback
  - Add-on ID: plugin.switchback
  - Version number: 1.0.0
  - Kodi/repository version: nexus

- **Code location**
  - URL: https://github.com/bossanova808/plugin.switchback/
  

Kodi utility for fast switching between recently played media.

Keeps a list of recently played media - supports Kodi library episodes, movies, PVR channels, songs and non-library files.  Does not (yet?) support add-ons or PVR recordings.

The primary intended use is to make for super easy Switchback between two in progress videos (by binding a remote key to Switchback, see Wiki/Forum thread for info).

Consider this scenario:
- You are watching 'video A' with your partner.  You are interrupted and your partner needs to tend to the kids/howl at the moon.
- You navigate to 'video B' and watch some of that.
- Your partner comes back.
- You hit your one button 'Switchback' and 'video A' starts playing again, no need for tedious navigation etc.
- You are interrupted again - the moon is so very bright tonight - hit your 'Switchback' to resume 'video B' immediately, again with one magic button and no tedious navigation.
        

### Description of changes:

            v1.0.0 Initial release
        

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

2024-11-11 06:45 UTC, bossanova808 commented
@basrieter As requested, now a PR to Nexus branch.

2024-11-11 22:54 UTC, basrieter requested changes
Please have a look at my comments.

2024-11-11 22:54 UTC, basrieter commented on plugin.switchback/resources/lib/playback.py
> +        return json.dumps(self, default=lambda o: o.__dict__)
I would just return a dictionary here and do the dumping to string in the place where you save stuff.

2024-11-11 22:54 UTC, basrieter commented on plugin.switchback/resources/lib/store.py
> +            temp_json = []
Use my previous comment and let `toJson` return a dictionary and then just do a `json.dumps` of the full array here.

2024-11-11 22:54 UTC, basrieter commented on plugin.switchback/resources/lib/switchback_service.py
> +            xbmc.sleep(500)
Use `Store.kodi_event_monitor.waitForAbort` here.

2024-11-11 23:38 UTC, bossanova808 commented
I think that is all addressed.  

(I'm not really super clear on the `waitForAbort` vs `sleep` behaviour but let me know if this isn't right!)

2024-11-14 22:38 UTC, basrieter approved these changes

2024-11-14 22:38 UTC, basrieter commented
Thanks for you contribution!

2024-11-14 22:38 UTC, merged